### ISSUE TITLE
Рубрика "Отцы"

### ISSUE THREAD

**Issue by egorshulga** [deazbuka/deazbuka.github.io#2]
Спасибо за этот замечательный алфавитный указатель азбуки! Только появилось желание пройти по всем выпускам азбуки, как этот список появился в максимальном удобном виде.

Вопрос: что вы думаете насчёт рубрики "Отцы"? Можно ли его добавить как-то рядом с алфавитным указателем азбуки?

**Comment by KarKarbI4** [comment]
Привет!

Пока что в планах только допилить процесс обновления данных для Азбуки и запаблишить исходный код, который всем этим делом занимается, на всеобщее обозрение :)

Затем, применю написанный для Азбуки автоматический парсер для Отцов и посмотрю, хорошо ли они определяются.
Если ручной работы после этого останется не очень много (в Азбуке получилось примерно 120 автоматически спарсеных таймстемпов и 25 ручных), подумаю, можно ли их как-то их наглядно и аккуратно отобразить)

Думаю, в ближайшее время ждать не стоит :(

**Comment by egorshulga** [comment]
Тем не менее, супер 👍 Там уже сейчас столько материала, что хватит и на ближайшее время, и на более далёкое.

Кажется, что Отцы, как правило, связаны с терминами Азбуки, поэтому, наверное, их можно попытаться подложить к тем же терминам в списке.

Круто, что есть возможность автоматизировать процесс сбора. В сборе целая энциклопедия политологии получится
